Add leaderboard materialized view
safe-global/safe-locking-service pull request #128
Opened 2024-06-05 09:50 UTC by fmrsabino

Closes #102 

- Add a new Django command to update or create a materialized view that contains the leaderboards for all campaigns.
- Refreshing the leaderboards happen with the following actions:
  * A CSV with new activities is uploaded
  * The command `python manage.py update_leaderboard_view` is executed.
- The materialized view is stored under `campaign_leaderboards` with an index on the `address` and `campaign_uuid`.
- Updates the view query to get the leaderboard position so that it uses the new materialized view instead.

2024-06-05 09:50 UTC, fmrsabino commented
Converting to draft as it's missing one migration.

2024-06-05 13:06 UTC, fmrsabino commented on safe_locking_service/campaigns/migrations/0002_add_materialized_view.py
> +        ("campaigns", "0001_initial"),
Need to change the dependency of this migration due to a recent merge https://github.com/safe-global/safe-locking-service/commit/c187e6e4e3a35b2a51e42f804485db88a0cad4b2

2024-06-05 16:18 UTC, fmrsabino commented on safe_locking_service/campaigns/management/commands/update_leaderboard_view.py
> +    help = "Update the leaderboard view for a campaign"
Should be "for all campaigns"

2024-06-06 09:49 UTC, Uxio0 requested changes

2024-06-06 11:24 UTC, moisses89 requested changes

2024-06-06 11:24 UTC, moisses89 commented on safe_locking_service/campaigns/tasks.py
> +            update_leaderboard_view()
For me is a little bit weird call a command function from a celery task.

2024-06-06 11:24 UTC, moisses89 commented on safe_locking_service/campaigns/tasks.py
> +            update_leaderboard_view()
I'm not sure about this update, do you think that is needed every time recheck if the view was created?
I think that would be more django style add a migration that creates the materialized view and a back migration that removes the materialized view.
The update function can just call the REFRESH MATERIALIZED VIEW.

2024-06-06 13:07 UTC, fmrsabino commented on safe_locking_service/campaigns/models.py
> +    SELECT * FROM campaign_leaderboards WHERE campaign_uuid=%s AND address=%s
Sorry should have added this to the description. I tried an initial version using Django ORM before opening the Pull Request but faced some issues. A primary key is required by the ORM. However I don't think we can have composite primary keys in Django. I would uniquely identify each row of the materialised view as a combination of `address` and `campaign_uuid`

An autogenerated primary key also seems wrong and potentially unstable given that the view can be refreshed. What do you think?

2024-06-06 14:00 UTC, fmrsabino commented on safe_locking_service/campaigns/tasks.py
> +            update_leaderboard_view()
The way it is right now the query is idempotent. The advantage of this is that, besides having the same final state, the query logic is condensed in a single place (both for creation and refreshing). This logic can then be used from multiple places without having to check if the view is created or not.

However I do get your point that the Django application would assume that all migrations needs to be executed. I don't have a strong opinion on this one so if you prefer to keep the command simpler I can change it 👍

2024-06-06 14:04 UTC, fmrsabino commented on safe_locking_service/campaigns/tasks.py
> +            update_leaderboard_view()
While the codebase is also bundled with the Celery task, I think actually having an "external" interface that calls a function of another component is better. Like:

```
Celery (Python codebase) --- via command  ----> Web/Django (Python codebase)
```

2024-06-06 14:13 UTC, fmrsabino commented on safe_locking_service/campaigns/management/commands/update_leaderboard_view.py
> +import logging
The `update_leaderboard_view.py` is the command itself so timeouts when calling the command would need to be handled by the caller.

For example, we call the command when doing a CSV upload. In this case, the command is called within a DB transaction so that means that if there's a timeout we do roll back the latest "activity update". So the view should be consistent.

Calling the command manually should only be required if the database changes via the Admin (which is not intended right now). So if I add a new single Activity via the Admin Panel then the view needs to be manually updated . But Activities are meant to be created only via the CSV upload (the source of truth).

2024-06-06 14:26 UTC, fmrsabino commented on safe_locking_service/campaigns/tasks.py
> +            update_leaderboard_view()
Address in [a24dc03](https://github.com/safe-global/safe-locking-service/pull/128/commits/a24dc03b0edf3316c5eb388d4c5b64100e5134b7)

We have aligned internally and decided to have the migration as the only place that creates the view. This means that the command won't work until all the migrations are executed which is also considered the correct behaviour.

2024-06-06 14:52 UTC, moisses89 approved these changes

2024-06-07 15:20 UTC, Uxio0 commented on safe_locking_service/campaigns/models.py
> +    SELECT * FROM campaign_leaderboards WHERE campaign_uuid=%s AND address=%s
Ok, works for me then, makes sense!

2024-06-10 08:57 UTC, Uxio0 approved these changes

2024-06-10 09:01 UTC, merged