Add view to process and create Activities
safe-global/safe-locking-service pull request #91
Opened 2024-05-10 09:47 UTC by fmrsabino

Closes #82

- A new view was added to allow for uploading and processing the given CSV. The view is under: `<BASE_URL>/api/v1/campaigns/upload`.
- Adds the `Activity` model – this model describes an activity of an address that can result in points. An activity is tied to a single `Campaign`.
- Removes the CSV helper – it was added based on the assumption that it could be used in more places. This was replaced by a direct usage of `csv.DictReader`

2024-05-10 09:54 UTC, fmrsabino commented on safe_locking_service/campaigns/views.py
> +def upload_file_view(request) -> HttpResponse:
As a future reference: It would also be nice to have this view linked in the admin page itself.

2024-05-10 11:39 UTC, moisses89 commented on config/urls.py
> +        include("safe_locking_service.campaigns.urls", namespace="campaigns"),
@fmrsabino I think that would be better add this behind the admin/ path instead behind the api.

2024-05-10 11:44 UTC, fmrsabino commented on config/urls.py
> +        include("safe_locking_service.campaigns.urls", namespace="campaigns"),
> @fmrsabino I think that would be better add this behind the admin/ path instead behind the api.

I have no strong opinion on this. Can be seen as an admin action in the end yes 👍

2024-05-10 13:43 UTC, fmrsabino commented on safe_locking_service/campaigns/views.py
> +        )
Here we assume that this will be successful. We should consider if we want to skip invalid ones or do a bulk insert in the context of a transaction (i.e.: all or nothing).

@moisses89

2024-05-14 10:46 UTC, moisses89 commented on config/settings/base.py
> +            {"queue": "events"},
we can use default queue for this tasks, could be confusing in the future as events is related with blockchain events indexing.

2024-05-14 10:46 UTC, moisses89 commented on safe_locking_service/campaigns/models.py
> +    slug = models.SlugField()
Which is the purpose of the slug field?

2024-05-14 10:46 UTC, moisses89 commented on safe_locking_service/campaigns/models.py
> +    boosted_points_rank = models.PositiveIntegerField()
I think that we don't need this agregated data, we can calculate them from Select query. 
```
 total_boosted_points = models.DecimalField(max_digits=15, decimal_places=8)
 points_rank = models.PositiveIntegerField()
 boosted_points_rank = models.PositiveIntegerField()
```

2024-05-14 10:46 UTC, moisses89 commented on safe_locking_service/campaigns/models.py
> +    # TODO uniqueness of the campaign
I'd do this now, to avoid future migrations. 
We should force the unique name and generate an identifier from the name, this will be needed for the campaigns/campaignID endpoint.

2024-05-14 21:10 UTC, fmrsabino commented on config/settings/base.py
> +            {"queue": "events"},
Changed in [03b8890](https://github.com/safe-global/safe-locking-service/pull/91/commits/03b88907f32ce21111b0492a64bf2a957eed18c2)

2024-05-14 21:16 UTC, fmrsabino commented on safe_locking_service/campaigns/models.py
> +    slug = models.SlugField()
The purpose of the slug field is to have a label that can be used in URLs. This can be useful on REST Apis if we want to use this field as a lookup field and not a numerical id.

https://docs.djangoproject.com/en/5.0/ref/models/fields/#slugfield

2024-05-14 21:17 UTC, fmrsabino commented on safe_locking_service/campaigns/models.py
> +    boosted_points_rank = models.PositiveIntegerField()
Addressed in https://github.com/safe-global/safe-locking-service/pull/94

2024-05-14 21:18 UTC, fmrsabino commented on safe_locking_service/campaigns/models.py
> +    # TODO uniqueness of the campaign
It was not addressed in https://github.com/safe-global/safe-locking-service/pull/94 but we would need to have a new migration either way because the `Campaign` field was already pushed.

2024-05-15 10:29 UTC, moisses89 requested changes

2024-05-15 10:29 UTC, moisses89 commented on safe_locking_service/campaigns/views.py
> +    tasks.process_csv_task.delay(period.id, activities_list)
Could be possible to encapsulate this functions in a `class` something like class view of restframework?

2024-05-15 10:29 UTC, moisses89 commented on safe_locking_service/campaigns/views.py
> +                error_message = f"Invalid CSV format: {e}"
This message will be loged?

2024-05-15 13:10 UTC, fmrsabino commented on safe_locking_service/campaigns/tasks.py
> +            period.activities.all().delete()
There shouldn't be any issues deleting all activities in the beginning. I'm accessing the `activities` via the `period` so this should delete all the activities for that `Period` only 🤔

2024-05-15 13:20 UTC, fmrsabino commented on safe_locking_service/campaigns/views.py
> +    tasks.process_csv_task.delay(period.id, activities_list)
This should be possible. Can this be tackled in a separate PR as in would change the structure of the view + tests (as we have already the functionality in and working)?

2024-05-15 13:24 UTC, fmrsabino commented on safe_locking_service/campaigns/views.py
> +                error_message = f"Invalid CSV format: {e}"
Message was not logged, just shown to the user. Added a log here: [76c24cc](https://github.com/safe-global/safe-locking-service/pull/91/commits/76c24cc24cad0b15de351a677a792e58deb7cad8)

2024-05-15 13:24 UTC, fmrsabino commented on safe_locking_service/campaigns/tasks.py
> +def process_csv_task(period_id, activities_list):
Added types and documentation here: [76c24cc](https://github.com/safe-global/safe-locking-service/pull/91/commits/76c24cc24cad0b15de351a677a792e58deb7cad8)

2024-05-15 15:33 UTC, fmrsabino commented on safe_locking_service/campaigns/tasks.py
> +            period.activities.all().delete()
I don't think removing activities is "wrong" because the file is supposed to have the final state for the period. The more complex alternative would be to compute a diff of: updates, additions, deletions and trigger those separately (but the end result should still be the same).

2024-05-16 07:30 UTC, moisses89 approved these changes

2024-05-16 08:01 UTC, merged