Add admin action to upload period data
safe-global/safe-locking-service pull request #97
Opened 2024-05-16 08:28 UTC by fmrsabino

- Allows uploading data for a given period via an admin action. [^1]
- Only one period is allowed to be selected. An error is shown to the user if more periods are selected.
- The view triggered on the action is tied to `GET /api/v1/campaigns/upload/?period_slug=<period_slug>`
  * If the view is loaded with a `period_slug` query parameter, the picker will only have that entry selected. [^2]
  * If no query parameter is provided, any period can be selected. [^3]

[^1]: <img width="472" alt="image" src="https://github.com/safe-global/safe-locking-service/assets/3332770/723d29a6-ba7e-4116-972b-781dccee5f42">

[^2]:<img width="727" alt="image" src="https://github.com/safe-global/safe-locking-service/assets/3332770/ed9a4b22-fa31-4cca-8b68-4e9f200cb4a1">

[^3]:<img width="724" alt="image" src="https://github.com/safe-global/safe-locking-service/assets/3332770/9c415771-73eb-43b9-9ea2-c9888219a174">

2024-05-20 08:51 UTC, moisses89 requested changes

2024-05-20 08:51 UTC, moisses89 commented on safe_locking_service/campaigns/admin.py
> +        reverse("v1:campaigns:activities_upload")
I would like to suggest to move this admin view to the admin path, at this way will be protected also by the oAuth.

2024-05-20 08:51 UTC, moisses89 commented on safe_locking_service/campaigns/forms.py
> +        if period_slug is not None:
```suggestion
        if period_slug:
```

2024-05-21 08:29 UTC, fmrsabino commented on safe_locking_service/campaigns/forms.py
> +        if period_slug is not None:
Done [757a341](https://github.com/safe-global/safe-locking-service/pull/97/commits/757a3416a54bc4c8c6fa3b649fe938fc34dfaa36)

2024-05-21 08:35 UTC, fmrsabino commented on safe_locking_service/campaigns/admin.py
> +        reverse("v1:campaigns:activities_upload")
The "issue" with moving this to the `admin` path is that the URLs and views listed here are under the `/api/v1/campaigns` path.

So in order to move this to the admin path we'd need to specify the URL from the root URL configuration but that'd would assume that the app is bundled with the root app.

I can look into how to "inject" the admin URL from the "campaigns" application into the root URL configuration.

Maybe on a different PR what do you think? (we can also add this path to the OAuth rule)

2024-05-21 08:50 UTC, moisses89 commented on safe_locking_service/campaigns/admin.py
> +        reverse("v1:campaigns:activities_upload")
I agree to do it in a different PR, and also ensure that will be added to oAuth in production before release. 
I mean remove it from campaigns path and add it to admin path.
`path(settings.ADMIN_URL,include(upload_url)),`

2024-05-21 09:51 UTC, merged